name = "lokmanya-tilak-college-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production]
name = "lokmanya-tilak-college-api"

[[kv_namespaces]]
binding = "COLLEGE_DB"
id = "773d02774f2248079037ac201e67cf49"

[vars]
ENVIRONMENT = "production"
