name = "lokmanya-tilak-college-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production]
name = "lokmanya-tilak-college-api"

[[kv_namespaces]]
binding = "COLLEGE_DB"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[vars]
ENVIRONMENT = "production"
